// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webGDPR.Data;

namespace webGDPR.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190108201032_productstock")]
    partial class productstock
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("webGDPR.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("Name");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("webGDPR.Models.Base", b =>
                {
                    b.Property<string>("BaseId")
                        .ValueGeneratedOnAdd();

                    b.Property<byte>("BaseNumber");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("Deleted");

                    b.Property<string>("Description");

                    b.Property<string>("HWId");

                    b.Property<string>("LastStatusId");

                    b.Property<string>("Name");

                    b.Property<string>("Text");

                    b.Property<string>("UserId");

                    b.HasKey("BaseId");

                    b.HasIndex("LastStatusId");

                    b.ToTable("Base");
                });

            modelBuilder.Entity("webGDPR.Models.BaseStatus", b =>
                {
                    b.Property<string>("BaseStatusId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BaseId");

                    b.Property<int>("Battery");

                    b.Property<string>("ConnectedTo");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("HasBattery");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsCharging");

                    b.Property<bool>("IsConnected");

                    b.Property<bool>("IsPlugged");

                    b.Property<int>("Radio");

                    b.Property<string>("UserId");

                    b.HasKey("BaseStatusId");

                    b.HasIndex("ConnectedTo");

                    b.ToTable("BaseStatus");
                });

            modelBuilder.Entity("webGDPR.Models.Collar", b =>
                {
                    b.Property<string>("CollarId")
                        .ValueGeneratedOnAdd();

                    b.Property<byte>("BaseNumber");

                    b.Property<byte>("CollarNumber");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("Deleted");

                    b.Property<string>("Description");

                    b.Property<string>("HWId");

                    b.Property<string>("LastStatusId");

                    b.Property<string>("Name");

                    b.Property<string>("UserId");

                    b.HasKey("CollarId");

                    b.HasIndex("LastStatusId");

                    b.ToTable("Collar");
                });

            modelBuilder.Entity("webGDPR.Models.CollarStatus", b =>
                {
                    b.Property<string>("CollarStatusId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Battery");

                    b.Property<string>("CollarId");

                    b.Property<string>("ConnectedTo");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsConnected");

                    b.Property<bool>("IsGPSConnected");

                    b.Property<int>("Radio");

                    b.Property<string>("UserId");

                    b.HasKey("CollarStatusId");

                    b.HasIndex("ConnectedTo");

                    b.ToTable("CollarStatus");
                });

            modelBuilder.Entity("webGDPR.Models.Device", b =>
                {
                    b.Property<string>("DeviceId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AliasName");

                    b.Property<bool>("Banned");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsLogging");

                    b.Property<string>("Manufacturer");

                    b.Property<string>("Model");

                    b.Property<string>("Name");

                    b.Property<string>("OSVersion");

                    b.Property<string>("Platform");

                    b.Property<string>("Type");

                    b.Property<string>("UserId");

                    b.HasKey("DeviceId");

                    b.ToTable("Device");
                });

            modelBuilder.Entity("webGDPR.Models.DeviceLog", b =>
                {
                    b.Property<string>("DeviceLogId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("DeviceId");

                    b.Property<string>("Message");

                    b.Property<string>("Reason");

                    b.HasKey("DeviceLogId");

                    b.ToTable("DeviceLog");
                });

            modelBuilder.Entity("webGDPR.Models.Invoice", b =>
                {
                    b.Property<string>("InvoiceId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("Deleted");

                    b.Property<DateTime>("DeliveryDate");

                    b.Property<bool>("IsWishList");

                    b.Property<DateTime>("OrderDate");

                    b.Property<decimal>("TotalOrder");

                    b.HasKey("InvoiceId");

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("webGDPR.Models.InvoiceItem", b =>
                {
                    b.Property<string>("InvoiceItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comment");

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("InvoiceId");

                    b.Property<decimal>("Price");

                    b.Property<string>("ProductId");

                    b.Property<int>("Quantity");

                    b.HasKey("InvoiceItemId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceItem");
                });

            modelBuilder.Entity("webGDPR.Models.Pet", b =>
                {
                    b.Property<string>("PetId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Age");

                    b.Property<DateTime>("Birthdate");

                    b.Property<string>("Breeding");

                    b.Property<string>("Color");

                    b.Property<DateTime>("CreationDate");

                    b.Property<int>("DefaultMode");

                    b.Property<bool>("Deleted");

                    b.Property<string>("HealthComments");

                    b.Property<string>("LastCollarId");

                    b.Property<string>("LastModeId");

                    b.Property<string>("LastTrackingInfoId");

                    b.Property<string>("Name");

                    b.Property<string>("Type");

                    b.Property<string>("UserId");

                    b.Property<string>("Weigth");

                    b.HasKey("PetId");

                    b.HasIndex("LastCollarId");

                    b.HasIndex("LastModeId");

                    b.HasIndex("LastTrackingInfoId");

                    b.ToTable("Pet");
                });

            modelBuilder.Entity("webGDPR.Models.PetCollar", b =>
                {
                    b.Property<string>("PetCollarId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CollarId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<DateTime>("EndDate");

                    b.Property<bool>("IsActive");

                    b.Property<string>("PetId");

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("UserId");

                    b.HasKey("PetCollarId");

                    b.HasIndex("CollarId");

                    b.HasIndex("PetId");

                    b.ToTable("PetCollar");
                });

            modelBuilder.Entity("webGDPR.Models.PetMode", b =>
                {
                    b.Property<string>("PetModeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CollarId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<DateTime>("EndDate");

                    b.Property<bool>("IsActive");

                    b.Property<string>("PetId");

                    b.Property<DateTime>("StartDate");

                    b.Property<int>("Type");

                    b.Property<string>("UserId");

                    b.HasKey("PetModeId");

                    b.ToTable("PetMode");
                });

            modelBuilder.Entity("webGDPR.Models.PetTrackingInfo", b =>
                {
                    b.Property<string>("PetTrackingInfoId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Acceleration");

                    b.Property<string>("CollarId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsActive");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<string>("PetId");

                    b.Property<string>("UserId");

                    b.HasKey("PetTrackingInfoId");

                    b.HasIndex("CollarId");

                    b.HasIndex("PetId");

                    b.ToTable("PetTrackingInfo");
                });

            modelBuilder.Entity("webGDPR.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Body");

                    b.Property<string>("Images");

                    b.Property<string>("Title");

                    b.Property<string>("UserId");

                    b.HasKey("PostId");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("webGDPR.Models.Product", b =>
                {
                    b.Property<string>("ProductId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category");

                    b.Property<DateTime>("CreationDate");

                    b.Property<float>("Deep");

                    b.Property<bool>("Deleted");

                    b.Property<string>("Description");

                    b.Property<float>("Height");

                    b.Property<string>("Model");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.Property<int>("QuantityInStock");

                    b.Property<string>("Text");

                    b.Property<float>("Weight");

                    b.Property<float>("Width");

                    b.HasKey("ProductId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("webGDPR.Models.User", b =>
                {
                    b.Property<string>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("OwnerID");

                    b.HasKey("UserID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("webGDPR.Data.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("webGDPR.Data.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("webGDPR.Data.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("webGDPR.Data.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("webGDPR.Models.Base", b =>
                {
                    b.HasOne("webGDPR.Models.BaseStatus", "LastStatus")
                        .WithMany()
                        .HasForeignKey("LastStatusId");
                });

            modelBuilder.Entity("webGDPR.Models.BaseStatus", b =>
                {
                    b.HasOne("webGDPR.Models.Device", "DeviceConnectedTo")
                        .WithMany()
                        .HasForeignKey("ConnectedTo");
                });

            modelBuilder.Entity("webGDPR.Models.Collar", b =>
                {
                    b.HasOne("webGDPR.Models.CollarStatus", "LastStatus")
                        .WithMany()
                        .HasForeignKey("LastStatusId");
                });

            modelBuilder.Entity("webGDPR.Models.CollarStatus", b =>
                {
                    b.HasOne("webGDPR.Models.Base", "BaseConnectedTo")
                        .WithMany()
                        .HasForeignKey("ConnectedTo");
                });

            modelBuilder.Entity("webGDPR.Models.InvoiceItem", b =>
                {
                    b.HasOne("webGDPR.Models.Invoice")
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId");
                });

            modelBuilder.Entity("webGDPR.Models.Pet", b =>
                {
                    b.HasOne("webGDPR.Models.PetCollar", "LastCollar")
                        .WithMany()
                        .HasForeignKey("LastCollarId");

                    b.HasOne("webGDPR.Models.PetMode", "LastMode")
                        .WithMany()
                        .HasForeignKey("LastModeId");

                    b.HasOne("webGDPR.Models.PetTrackingInfo", "LastTrackingInfo")
                        .WithMany()
                        .HasForeignKey("LastTrackingInfoId");
                });

            modelBuilder.Entity("webGDPR.Models.PetCollar", b =>
                {
                    b.HasOne("webGDPR.Models.Collar", "Collar")
                        .WithMany()
                        .HasForeignKey("CollarId");

                    b.HasOne("webGDPR.Models.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId");
                });

            modelBuilder.Entity("webGDPR.Models.PetTrackingInfo", b =>
                {
                    b.HasOne("webGDPR.Models.Collar", "Collar")
                        .WithMany()
                        .HasForeignKey("CollarId");

                    b.HasOne("webGDPR.Models.Pet")
                        .WithMany("TrackingInfos")
                        .HasForeignKey("PetId");
                });
#pragma warning restore 612, 618
        }
    }
}
